[OPS-1003] acme.sh: let configured group access the certificate
serokell/serokell.nix pull request #12
Opened 2020-11-25 13:52 UTC by zhenyavinogradov

acme.sh allows setting a group for the certificate directory, but the
mode needs to be changed to let the group actually access it.

This change does not make existing setups less secure, because the group
is 'root' by default.

2020-12-16 11:46 UTC, balsoft approved these changes

2020-12-16 14:04 UTC, mkaito requested changes
I don't think it needs to be group writable.

2020-12-17 06:19 UTC, zhenyavinogradov commented
Changed it to `750`

2021-01-13 16:16 UTC, mkaito approved these changes

2021-01-14 07:55 UTC, merged